// export default {
//   login: "andersonmarquees",
//   id: 49351999,
//   node_id: "MDQ6VXNlcjQ5MzUxOTk5",
//   avatar_url: "https://avatars.githubusercontent.com/u/49351999?v=4",
//   gravatar_id: "",
//   url: "https://api.github.com/users/andersonmarquees",
//   html_url: "https://github.com/andersonmarquees",
//   followers_url: "https://api.github.com/users/andersonmarquees/followers",
//   following_url:
//     "https://api.github.com/users/andersonmarquees/following{/other_user}",
//   gists_url: "https://api.github.com/users/andersonmarquees/gists{/gist_id}",
//   starred_url:
//     "https://api.github.com/users/andersonmarquees/starred{/owner}{/repo}",
//   subscriptions_url:
//     "https://api.github.com/users/andersonmarquees/subscriptions",
//   organizations_url: "https://api.github.com/users/andersonmarquees/orgs",
//   repos_url: "https://api.github.com/users/andersonmarquees/repos",
//   events_url: "https://api.github.com/users/andersonmarquees/events{/privacy}",
//   received_events_url:
//     "https://api.github.com/users/andersonmarquees/received_events",
//   type: "User",
//   site_admin: false,
//   name: "Anderson Marques",
//   company: null,
//   blog: "",
//   location: "São Paulo",
//   email: null,
//   hireable: true,
//   bio: null,
//   twitter_username: "Anderso67259959",
//   public_repos: 29,
//   public_gists: 0,
//   followers: 0,
//   following: 0,
//   created_at: "2019-04-06T21:36:26Z",
//   updated_at: "2021-05-28T19:53:52Z",
// };

export default {
  login: "john-smilga",
  id: 42133389,
  node_id: "MDQ6VXNlcjQyMTMzMzg5",
  avatar_url: "https://avatars.githubusercontent.com/u/42133389?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/john-smilga",
  html_url: "https://github.com/john-smilga",
  followers_url: "https://api.github.com/users/john-smilga/followers",
  following_url:
    "https://api.github.com/users/john-smilga/following{/other_user}",
  gists_url: "https://api.github.com/users/john-smilga/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/john-smilga/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/john-smilga/subscriptions",
  organizations_url: "https://api.github.com/users/john-smilga/orgs",
  repos_url: "https://api.github.com/users/john-smilga/repos",
  events_url: "https://api.github.com/users/john-smilga/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/john-smilga/received_events",
  type: "User",
  site_admin: false,
  name: "John Smilga",
  company: "Coding Addict",
  blog: "www.johnsmilga.com",
  location: "Los Angeles",
  email: null,
  hireable: null,
  bio: "Creator of Coding Addict",
  twitter_username: "john_smilga",
  public_repos: 214,
  public_gists: 0,
  followers: 5388,
  following: 0,
  created_at: "2018-08-06T06:48:23Z",
  updated_at: "2021-05-19T16:44:20Z",
};
